In [11]:
from collections import OrderedDict
temps = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5)]
def check(temps):
    ordered_dict_temps = OrderedDict(temps)
    print(sorted(ordered_dict_temps, key = lambda x: x[1], reverse = True))
check(temps)

['2000', '2001', '2002', '2003']


In [32]:
# Напишите функцию brackets(line), которая определяет, является ли последовательность из круглых скобок line правильной.

# Примечание 1. Какая последовательность скобок правильная?

# Правильной скобочной последовательностью назовём такую последовательность скобок, 
# в которой для каждой открывающей скобки есть последующая соответствующая ей закрывающая скобка. 
# Соответственно, остальные скобочные последовательности назовём неправильными. Пустую строку будем считать правильной последовательностью.

# Примечание 2.Для решения этой задачи потребуется использовать стек.

# Посимвольно переберите строку. Если встретилась открывающаяся скобка, положите её в стек. Если встретилась закрывающаяся скобка, извлеките скобку из стека.

# Если стек пустой, то есть извлечь скобку нельзя, последовательность неправильная.
# Если строка закончилась и стек стал пустым, последовательность правильная.
# Если в стеке остались скобки, последовательность неправильная.
# Пример


# print(brackets("(()())"))
# # True
# print(brackets(""))
# # True
# print(brackets("(()()))"))
# # False
from collections import deque
def brackets(line):
    deque_count = deque()
    for symbol in line:
        if symbol == '(':
            deque_count.append(symbol)
            print(deque_count)
        elif symbol == ')':
            if not deque_count:
                return False
            deque_count.pop()
            print(deque_count)
    if len(deque_count) == 0:
        return True
    else:
        return False
    

print(brackets("(()())"))

deque(['('])
deque(['(', '('])
deque(['('])
deque(['(', '('])
deque(['('])
deque([])
True


In [13]:
# Дан список кортежей ratings с рейтингами кафе. Кортеж состоит из названия и рейтинга кафе.

# Необходимо отсортировать кортеж по убыванию рейтинга. Если рейтинги совпадают, то отсортировать кафе дополнительно по названию в алфавитном порядке.

# Получите словарь cafes с упорядоченными ключами из отсортированного списка, где ключи — названия кафе, а значения — их рейтинг.

ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
    
cafes = dict(sorted(ratings, key=lambda x: (-x[1], x[0])))
print(cafes)

{'WokAndRice': 4.9, 'WokToWork': 4.9, 'General Foods': 4.8, 'New Age': 4.6, 'Belissimo': 4.5, 'CakeAndCoffee': 4.2, 'CakeOClock': 4.2, 'CakeTime': 4.1, 'Nice Cakes': 3.9, 'Old Gold': 3.3, 'Old Wine Cellar': 3.3, 'Old York': 3.3}


In [18]:
from collections import OrderedDict
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
cafes = OrderedDict(sorted(ratings, key=lambda x: (-x[1], x[0])))  

print(cafes)

OrderedDict([('WokAndRice', 4.9), ('WokToWork', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Old York', 3.3)])


In [23]:
# Напишите функцию task_manager(tasks), которая принимает список задач tasks для нескольких серверов. 
# Каждый элемент списка состоит из кортежа (<номер задачи>, <название сервера>, <высокий приоритет задачи>).

# Функция должна создавать словарь и заполнять его задачами по следующему принципу: название сервера — ключ, 
# по которому хранится очередь задач для конкретного сервера.

# Если поступает задача без высокого приоритета (последний элемент кортежа — False), 
# добавить номер задачи в конец очереди. Если приоритет высокий, добавить номер в начало.

# Для словаря используйте defaultdict, для очереди — deque.

# Функция возвращает полученный словарь с задачами.

# Пример


tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]

# print(task_manager(tasks))
# defaultdict(, {'voltage': deque([41667, 35364]),
# 'office': deque([36871, 40690, 33850])})

from collections import defaultdict
from collections import deque

def task_manager(tasks):
    common_dict = defaultdict(deque)
    for number, server_name, priorety in tasks:
        if priorety:
            common_dict[server_name].appendleft(number)
        else:
            common_dict[server_name].append(number)
    return common_dict


defaultdict(<class 'collections.deque'>, {'office': deque([36871, 40690, 33850]), 'voltage': deque([41667, 35364])})


In [6]:
import numpy as np
np.iinfo(np.uint64)

iinfo(min=0, max=18446744073709551615, dtype=uint64)

In [7]:
a = 2*18446744073709551615
print(a)

36893488147419103230


In [21]:
a = -456
b = np.uint8(a)
print(b)

56


/var/folders/mj/6p8qfrq97ts_vlb1kk914kjc0000gn/T/ipykernel_92781/1891576283.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -456 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  b = np.uint8(a)


In [1]:
i=0
while True:
    i+=1
    if i == 2:
        continue
    if i == 5:
        break
    
    print(i)

1
3
4


In [18]:
import numpy as np
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step, 2))

0.45


In [26]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
                    [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
                    [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
                    [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
                    [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
                    [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)


elem_5_3 = mystery[4, 2]
last = mystery[-1,-1]
line_4 = mystery[3]
col_2 = mystery[:, -2]
part = mystery[1:4, 2:5]
rev = (mystery[:, -1])[::-1]
trans = mystery.transpose()

print(trans)

[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


In [2]:
import numpy as np
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

nans_index = np.isnan(mystery)
# print(nans_index)
n_nan = list(nans_index).count(True)
# print(n_nan)
mystery_new = mystery.copy()
mystery_new[np.isnan(mystery_new)] = 0
# print(mystery_new)
mystery_int = mystery.astype(np.int32)
# print(mystery_int)
# print(mystery)
array = np.sort(mystery)
# print(array)
table = array.reshape((5, 3), order='F')
print(table)
col = table[:,1]
print(col)


[[-26024.  -2365.  29810.]
 [-17722.  12279.  31244.]
 [-16431.  16132.     nan]
 [ -9212.  25933.     nan]
 [ -6974.  28745.     nan]]
[-2365. 12279. 16132. 25933. 28745.]


/var/folders/mj/6p8qfrq97ts_vlb1kk914kjc0000gn/T/ipykernel_1848/4109252169.py:13: RuntimeWarning: invalid value encountered in cast
  mystery_int = mystery.astype(np.int32)


In [4]:
np.random.rand(2, 3, 4, 2, 1, 2)

array([[[[[[0.08350894, 0.92723623]],

          [[0.47292693, 0.16186133]]],


         [[[0.12187943, 0.18873952]],

          [[0.03662364, 0.0600803 ]]],


         [[[0.53374364, 0.36398396]],

          [[0.08577924, 0.12018411]]],


         [[[0.62318787, 0.5957223 ]],

          [[0.74303621, 0.52068648]]]],



        [[[[0.64370833, 0.56862714]],

          [[0.26889178, 0.1640672 ]]],


         [[[0.7648853 , 0.39343206]],

          [[0.73592533, 0.7571759 ]]],


         [[[0.44085112, 0.95167922]],

          [[0.92168176, 0.86331502]]],


         [[[0.61992879, 0.53454097]],

          [[0.28332103, 0.61018418]]]],



        [[[[0.80258906, 0.82015134]],

          [[0.82081001, 0.8734404 ]]],


         [[[0.24744434, 0.89942496]],

          [[0.73339455, 0.75232948]]],


         [[[0.44757524, 0.56633936]],

          [[0.16157717, 0.7300612 ]]],


         [[[0.83229181, 0.68466823]],

          [[0.01406286, 0.03469354]]]]],




       [[[[[0.49114767, 0.860842

In [5]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]


In [17]:
# адайте seed = 2021.

# Сохраните в переменные необходимые значения.

# Примечание 1. Не меняйте названия переменных и последовательность генерации случайных чисел в задании.

# Примечание 2. Не забудьте импортировать numpy и сразу задать seed = 2021

# В simple сохраните случайное число в диапазоне от 0 до 1
# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их в переменную randoms
# Получите массив из случайных целых чисел от 1 до 100 (включительно) из 3 строк и 2 столбцов. Сохраните результат в table
# В переменную even сохраните четные числа от 2 до 16 (включительно)
# Скопируйте even в переменную mix. Перемешайте числа в mix так, чтобы массив изменился
# Получите из even 3 числа без повторений. Сохраните их в переменную select
# Получите переменную triplet, которая должна содержать перемешанные значения из массива select (сам select измениться не должен)

import numpy as np
np.random.seed(2021)
simple = np.random.rand()
# print(simple)
randoms = np.random.uniform(-150, 2021, size = 120)
table = np.random.randint(1, 101, size = (3, 2))
# print(table)
even = np.arange(2, 17, 2)
# print(even)
mix = even.copy()
np.random.shuffle(mix)
# print(mix, even)
select = np.random.choice(even, size = 3, replace = False)
# print(select)
triplet = np.random.permutation(select)


In [60]:
# Напишите функцию get_chess, которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), 
# заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.

# Примечание: воспользуйтесь функцией zeros из библиотеки numpy, а затем с помощью срезов без циклов задайте необходимым элементам значение 1.

# Напоминание: в Python для получения каждого второго элемента используется срез [::2]. Подумайте, как грамотно применить этот принцип к двумерному массиву.

# Пример:

# get_chess(1)
# # array([[0.]])
# get_chess(4)
# # array([[0., 1., 0., 1.],
# #        [1., 0., 1., 0.],
# #        [0., 1., 0., 1.],
# #        [1., 0., 1., 0.]])

def get_chess(a):
    a_sqr = np.zeros((a, a))
    a_sqr[::2, 1::2] = 1
    a_sqr[1::2, ::2] = 1
    return a_sqr
    
get_chess(5)
    

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

In [72]:
# Вы разрабатываете приложение для прослушивания музыки. 
# Конечно же, там будет доступна функция перемешивания плейлиста. 
# Пользователю может настолько понравиться перемешанная версия плейлиста, 
# что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, 
# а просто хотите сохранять тот seed, с которым он был сгенерирован.

# Для этого напишите функцию shuffle_seed(<array>),  
# которая принимает на вход массив из чисел, 
# генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) 
# и возвращает кортеж: перемешанный с данным seed массив 
# (исходный массив должен оставаться без изменений), 
# а также seed, с которым этот массив был получен.

# Пример:

# array = [1, 2, 3, 4, 5]
# shuffle_seed(array)
# # (array([1, 3, 2, 4, 5]), 2332342819)
# shuffle_seed(array)
# # (array([4, 5, 2, 3, 1]), 4155165971)

import numpy as np
def shuffle_seed(a):
    func_seed = np.random.randint(0, 2**32 - 1)
    np.random.seed(func_seed)
    return((np.random.permutation(a), func_seed ))

array = [1, 2, 3, 4, 5]
shuffle_seed(array)

(array([5, 4, 3, 2, 1]), 3100716767)

In [ ]:
# Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую. 
# Гарантируется, что все векторы, которые передаются, одинаковой длины.

# Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

# Пример:

# vec1 = np.array([1,2,3])
# vec2 = np.array([4,5,6])
# vec3 = np.array([7, 8, 9])
 
# min_max_dist(vec1, vec2, vec3)
# # (5.196152422706632, 10.392304845413264)

import numpy as np

def min_max_dist(*vectors):
    vectors = np.array(vectors)
    dist = []
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            dist.append(np.linalg.norm(vectors[i] - vectors[j]))

            
    return (min(dist), max(dist))

            
    

In [ ]:
# Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. 
# Гарантируется, что все векторы, которые передаются, одинаковой длины.

# Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

# Пример:

# vec1 = np.array([2, 1])
# vec2 = np.array([-1, 2])
# vec3 = np.array([3,4])
# print(any_normal(vec1, vec2, vec3))
# # True

def any_normal(*vectors):
    vectors = np.array(vectors)
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            scalar = np.dot(vectors[i], vectors[j])
            if scalar == 0:
                return True
    return False

In [ ]:
# Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). 
# Это поля для игры в лото.

# Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

# Функция возвращает полученный массив.

# Пример:

# get_loto(3)
# Результат:

# array([[[ 35,  66,  38,  11,  32],
#        [ 32,   7,  37,  83,  42],
#        [ 89,  37,  19,  51,  89],
#        [ 70, 100,  83,   5,  11],
#        [ 20,  13,  60,  26,  41]],
 
#       [[ 23,  49,  76,  44,  43],
#        [ 59,  63,  99,  92,   2],
#        [ 83,   4,  25,  73,  19],
#        [ 10,  18,  40,  11,  21],
#        [ 58,  45,  73,  93,  61]],
 
#       [[100,  88,  70,  34,  51],
#        [  5,  35,  36,  85,  88],
#        [ 72,  23,  87,  30,  40],
#        [ 29,  21,  51,  73,  81],
#        [ 91,  19,  87,  60,  27]]])

import numpy as np

def get_loto(num):
    return np.random.randint(1, 101, (num, 5, 5), replace = 'F')
    

In [84]:

import numpy as np

def get_unique_loto(num):
    random_values = np.arange(1, 101)
    return_list = []
    for i in range(num):
        return_list.append(np.random.choice(random_values, ( 5, 5), replace=False))
    return_list = np.array(return_list)
    return return_list

get_unique_loto(10)

array([[[ 73,  52,  75,  22,  76],
        [ 88,  43,  25,  51,  56],
        [ 23,  85,  34,  40,  38],
        [ 87,  16,  21,  58,  80],
        [ 42,  46,  32,  27,  93]],

       [[ 34,  53,  51,  70, 100],
        [ 21,  27,  94,  28,  68],
        [ 22,   5,  59,  89,  79],
        [  8,  17,  41,   9,  24],
        [ 58,  38,  71,  56,  44]],

       [[ 21,  23,   9,  11,  41],
        [ 35,   1,  58,  65,  18],
        [ 45,  52,  75,  39,  87],
        [ 99,   5,  42,  40,  16],
        [ 27,  59,  97,  28,  77]],

       [[ 96,  92,  52,  61,  64],
        [100,  94,  53,  65,  44],
        [ 88,   2,   6,  30,  69],
        [ 21,  73,  41,   4,  95],
        [ 79,  58,  23,  48,  18]],

       [[ 33,  55,  51,   6,  74],
        [ 83,   8,  11,  28,   5],
        [ 15,  76,  70,  49,  68],
        [ 81,  32,  44,  47,  99],
        [ 17,  64,  37,  72,  19]],

       [[ 96,  12,  82,  59,  93],
        [ 72,  37,  64,  95,  43],
        [ 98,  62,  88,  71,  58],
        [ 

In [10]:
a = ['sdf', 'asda']
print(*a, sep=', ')
b = ', '.join(a)
print(b)

sdf, asda
sdf, asda
